# Etapa de construcción
FROM node:20.9.0 AS builder

WORKDIR /app

COPY package*.json ./
COPY . .

RUN npm uninstall next
RUN npm install next@latest

RUN npm install
RUN npm run build

# Etapa final
FROM node:20.9.0 AS final

WORKDIR /app

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/package*.json ./

EXPOSE 3000

CMD ["npm", "run", "start"]
