# Etapa de construcción
FROM node:20.9.0 AS builder

WORKDIR /app

COPY package*.json ./
COPY . .

RUN yarn global add next@latest
RUN yarn install

RUN yarn build

# Etapa final
FROM node:20.9.0 AS final

WORKDIR /app

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/package*.json ./

EXPOSE 3000

CMD ["yarn", "run", "start"]
