version: "3.8"
services:
    frontend:
        container_name: frontend
        build:
            context: .
            target: production
        restart: always
        environment:
            - NODE_ENV=production
        ports:
            - 2025:3000